[env:ulanzi]
platform = espressif32@6.3.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    fastled/FastLED@^3.6.0
    marcmerlin/FastLED NeoMatrix@^1.2

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
