[env:ulanzi]
platform = espressif32@6.3.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    fastled/FastLED@^3.6.0
    marcmerlin/FastLED NeoMatrix@^1.2
    adafruit/Adafruit BME280 Library@^2.2.0
    adafruit/Adafruit BMP280 Library@^2.6.0
    adafruit/Adafruit HTU21DF Library@^1.0.0
    adafruit/Adafruit SHT31 Library@^2.2.0
    links2004/WebSockets@^2.4.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
